# Generated by Django 3.0.5 on 2022-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Açıklama Başlığı', max_length=200, verbose_name='Name')),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('document', models.FileField(upload_to='products/katalog/%y/%m/%d')),
            ],
        ),
    ]
