# Generated by Django 3.0.5 on 2022-01-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0002_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Öğrenci', max_length=100)),
                ('paper', models.FileField(upload_to='products/%y/%m/%d')),
            ],
        ),
    ]
