# Generated by Django 3.0.5 on 2022-01-05 19:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211107_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=21),
            preserve_default=False,
        ),
    ]
