# Generated by Django 3.0.5 on 2022-01-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='info_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_tr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop_tr',
        ),
    ]
